openapi: 3.0.0
info:
  title: Sample API
  description: API documentation for a sample service
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Production Server
  - url: https://staging-api.example.com/v1
    description: Staging Server
paths:
  /items:
    get:
      summary: Retrieve a list of items
      description: Fetches all available items from the database
      operationId: getItems
      responses:
        "200":
          description: A list of items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Item"
        "500":
          description: Server Error
  /items/{id}:
    get:
      summary: Retrieve a single item
      description: Fetches an item by its ID
      operationId: getItemById
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the item to fetch
          schema:
            type: string
      responses:
        "200":
          description: Successfully retrieved the item
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        "404":
          description: Item not found
        "500":
          description: Server Error
components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: string
          example: "12345"
        name:
          type: string
          example: "Sample Item"
        price:
          type: number
          example: 29.99
        inStock:
          type: boolean
          example: true
        category:
          type: string
          example: "electronics"
