# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: song.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'song.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nsong.proto\x12\x12songRecommendation\"\x1e\n\x0bSongRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\";\n\x0cSongResponse\x12+\n\x05songs\x18\x01 \x03(\x0b\x32\x1c.songRecommendation.songBody\"H\n\x08songBody\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x02 \x01(\t\x12\x10\n\x08song_uri\x18\x03 \x01(\t\x12\x0c\n\x04rank\x18\x04 \x01(\r2]\n\x0bSongService\x12N\n\x07GetSong\x12\x1f.songRecommendation.SongRequest\x1a .songRecommendation.SongResponse\"\x00\x42\x03Z\x01.b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'song_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\001.'
  _globals['_SONGREQUEST']._serialized_start=34
  _globals['_SONGREQUEST']._serialized_end=64
  _globals['_SONGRESPONSE']._serialized_start=66
  _globals['_SONGRESPONSE']._serialized_end=125
  _globals['_SONGBODY']._serialized_start=127
  _globals['_SONGBODY']._serialized_end=199
  _globals['_SONGSERVICE']._serialized_start=201
  _globals['_SONGSERVICE']._serialized_end=294
# @@protoc_insertion_point(module_scope)
